services:
  anvil:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ANVIL_IP_ADDR=0.0.0.0
      - ANVIL_MNEMONIC=${ANVIL_MNEMONIC}
    ports:
      - "8545:8545"

  oracle:
    build: ./oracle-go
    depends_on:
      - anvil
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - FEED_ADDRESS=${FEED_ADDRESS}
      - CHAIN_ID=${CHAIN_ID}
    ports:
      - "8088:8088"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    depends_on:
      - anvil
    environment:
      - VITE_RPC_URL=${VITE_RPC_URL}
      - VITE_ORACLE_URL=${VITE_ORACLE_URL}
      - VITE_POOL_ADDRESS=${VITE_POOL_ADDRESS}
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules

volumes:
  app_node_modules:
